package com.route.domain.models.oee

data class OEE(
    val Date: String? = null,
    val Time: String? = null,
    val Shift: String? = null,
    val Machine: String? = null,
    val OperatorCode: String? = null,
    val PartNumber: String? = null,
    val cavityNumber: String? = null,
    val TotalProduced: String? = null,
    val WorkCav: String? = null,
    val CT: String? = null,
    val E: String? = null,
    val MO: String? = null,
    val H: String? = null,
    val ME: String? = null,
    val Q: String? = null,
    val DM: String? = null,
    val CO: String? = null,
    val SU: String? = null,
    val CM: String? = null,
    val R: String? = null,
    val WL: String? = null,
    val OTH: String? = null,
    val operation: String? = null,
)
